# Generated by Django 6.0.7 on 2026-07-21 14:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('timber', 'Timber'), ('finished', 'Finished Product')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('stock_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed price. Finished products only.', max_digits=10, null=True)),
                ('rate_per_m3', models.DecimalField(blank=True, decimal_places=2, help_text='Rate per cubic metre. Timber only.', max_digits=12, null=True)),
                ('species', models.CharField(blank=True, max_length=60)),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, help_text='inches', max_digits=6, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='inches', max_digits=6, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='feet', max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_per_piece', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sale')),
            ],
        ),
    ]
