# Generated by Django 6.0.7 on 2026-07-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
