# Generated by Django 6.0.7 on 2026-07-23 18:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_low_stock_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hanamel Timber', max_length=120)),
                ('kra_pin', models.CharField(blank=True, help_text='Seller KRA PIN', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('till_or_paybill', models.CharField(blank=True, help_text='M-Pesa Till or Paybill number', max_length=40)),
                ('footer_note', models.CharField(blank=True, default='Goods remain the property of the seller until paid in full.', max_length=200)),
            ],
            options={
                'verbose_name': 'Business profile',
                'verbose_name_plural': 'Business profile',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank transfer')], default='cash', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mpesa_receipt', models.CharField(blank=True, help_text='M-Pesa confirmation code, e.g. SFG4H2K9LM', max_length=32)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=140)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.sale')),
            ],
            options={
                'ordering': ['received_at'],
            },
        ),
    ]
